package main

import (
	"encoding/json"
	"fmt"
	"sync"

	"github.com/gorilla/websocket"
	"github.com/pion/webrtc/v4"
)

var (
	peerConnections = make(map[string]*webrtc.PeerConnection)
	dataChannels    = make(map[string]*webrtc.DataChannel)
	pcMutex         sync.Mutex
)

// Initialize a WebRTC PeerConnection when an offer is received from a dashboard viewer
func handleWebRTCOffer(ws *websocket.Conn, viewerId string, offer webrtc.SessionDescription) {
	config := webrtc.Configuration{
		ICEServers: []webrtc.ICEServer{
			{
				URLs: []string{"stun:stun.l.google.com:19302"},
			},
		},
	}

	pc, err := webrtc.NewPeerConnection(config)
	if err != nil {
		log("WebRTC Error: " + err.Error())
		return
	}

	pcMutex.Lock()
	peerConnections[viewerId] = pc
	pcMutex.Unlock()

	// Handle ICE candidates generated by the Agent
	pc.OnICECandidate(func(c *webrtc.ICECandidate) {
		if c == nil {
			return
		}
		candJSON, err := json.Marshal(c.ToJSON())
		if err != nil {
			return
		}
		ws.WriteJSON(Message{
			Type: "webrtc-ice-candidate",
			Data: map[string]interface{}{
				"candidate": string(candJSON),
				"target":    viewerId,
			},
		})
	})

	// Wait for the Dashboard to create a DataChannel
	pc.OnDataChannel(func(d *webrtc.DataChannel) {
		log(fmt.Sprintf("WebRTC DataChannel '%s' opened with Viewer %s", d.Label(), viewerId))

		d.OnOpen(func() {
			pcMutex.Lock()
			dataChannels[viewerId] = d
			pcMutex.Unlock()
			log("WebRTC Stream Ready for " + viewerId)
		})

		d.OnClose(func() {
			log("WebRTC DataChannel Closed for " + viewerId)
			pcMutex.Lock()
			delete(dataChannels, viewerId)
			pcMutex.Unlock()
		})
	})

	pc.OnConnectionStateChange(func(s webrtc.PeerConnectionState) {
		log(fmt.Sprintf("WebRTC State for %s: %s", viewerId, s.String()))
		if s == webrtc.PeerConnectionStateFailed || s == webrtc.PeerConnectionStateClosed {
			pcMutex.Lock()
			delete(peerConnections, viewerId)
			delete(dataChannels, viewerId)
			pcMutex.Unlock()
		}
	})

	// Set Remote Description (the Offer)
	if err := pc.SetRemoteDescription(offer); err != nil {
		log("WebRTC SetRemoteDescription Error: " + err.Error())
		return
	}

	// Create Answer
	answer, err := pc.CreateAnswer(nil)
	if err != nil {
		log("WebRTC CreateAnswer Error: " + err.Error())
		return
	}

	if err := pc.SetLocalDescription(answer); err != nil {
		log("WebRTC SetLocalDescription Error: " + err.Error())
		return
	}

	// Send Answer to Server to forward to Dashboard
	ws.WriteJSON(Message{
		Type: "webrtc-answer",
		Data: map[string]interface{}{
			"sdp":    answer.SDP,
			"type":   answer.Type.String(),
			"target": viewerId,
		},
	})
}

// Handle an ICE candidate received from the Dashboard
func handleWebRTCICECandidate(viewerId string, candidate webrtc.ICECandidateInit) {
	pcMutex.Lock()
	pc, ok := peerConnections[viewerId]
	pcMutex.Unlock()

	if ok {
		err := pc.AddICECandidate(candidate)
		if err != nil {
			log("WebRTC AddICECandidate Error: " + err.Error())
		}
	}
}

// Send a frame (base64 string) via all open WebRTC DataChannels
// Returns the number of channels sent to
func sendFrameOverWebRTC(frameB64 string) int {
	pcMutex.Lock()
	defer pcMutex.Unlock()

	count := 0
	msg := []byte(frameB64)
	for viewerId, dc := range dataChannels {
		if dc.ReadyState() == webrtc.DataChannelStateOpen {
			err := dc.Send(msg)
			if err != nil {
				log("WebRTC Send Error for " + viewerId + ": " + err.Error())
			} else {
				count++
			}
		}
	}
	return count
}
